// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Cr4QWwB8pOk8rPebXIfaNHuznm4zrFg',
    appId: '1:801492549425:web:8a32c51a083b99c1cb7a10',
    messagingSenderId: '801492549425',
    projectId: 'y-app-afbd6',
    authDomain: 'y-app-afbd6.firebaseapp.com',
    storageBucket: 'y-app-afbd6.appspot.com',
    measurementId: 'G-8QJCL5K50H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1z0S7q56NJF6xLj83v-cK-tVHyNOyHE',
    appId: '1:801492549425:android:020f08e453b08e5ecb7a10',
    messagingSenderId: '801492549425',
    projectId: 'y-app-afbd6',
    storageBucket: 'y-app-afbd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjaa3oJ5YwAzcL8IUMiTSOr3b_9V3aBw',
    appId: '1:801492549425:ios:93e2b74523b2f654cb7a10',
    messagingSenderId: '801492549425',
    projectId: 'y-app-afbd6',
    storageBucket: 'y-app-afbd6.appspot.com',
    iosBundleId: 'com.example.y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjaa3oJ5YwAzcL8IUMiTSOr3b_9V3aBw',
    appId: '1:801492549425:ios:523ee629877d5250cb7a10',
    messagingSenderId: '801492549425',
    projectId: 'y-app-afbd6',
    storageBucket: 'y-app-afbd6.appspot.com',
    iosBundleId: 'com.example.y.RunnerTests',
  );
}
